import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {contractRevision,validateBrandContract,checkBrandSources} from '../scripts/lib/brand-contract.mjs';
import {compileDeckPlan,inspectDeckPlan,compileDeckFile} from '../scripts/lib/deck-plan.mjs';
import {compileGoogleScene,verifyGoogleSceneReadback} from '../scripts/lib/google-slides.mjs';
import {renderPptxScene} from '../scripts/lib/pptx-render.mjs';
import {initWorkspace,buildWorkspace,verifiedBuild} from '../scripts/lib/workspace.mjs';
import {temporary} from './fixtures.mjs';
import {hash} from '../scripts/lib/common.mjs';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {fileURLToPath} from 'node:url';
const exec=promisify(execFile),plan=JSON.parse(await readFile(new URL('../examples/deck-plan.json',import.meta.url)));
export function syntheticBrand(){const colors={canvasPrimary:'#FFFFFF',canvasSecondary:'#F0F2F5',inkDeep:'#202124',inkSecondary:'#555555',headingPrimary:'#2867B2',accentAqua:'#2867B2'},role=(size,bold=false,colorRole='inkDeep')=>({size,bold,colorRole});const c={schema:1,identity:{id:'acme',variant:'light'},medium:{kind:'slides',delivery:'reading'},sources:[{path:'/synthetic/source',sha256:'a'.repeat(64)}],design:{fontFamily:'Arial',colors,slides:{canvas:{width:960,height:540},titleBox:{x:48,y:32,width:864,height:66},contentBox:{x:48,y:126,width:864,height:360},reservedBottom:486,spacing:{column:30,inset:18},typography:{title:role(28,true,'headingPrimary'),body:role(24),bodyReference:role(20),label:role(20,true),caption:role(14,false,'inkSecondary'),metric:role(64,true,'accentAqua'),quote:role(30)},chart:{seriesRoles:['headingPrimary','accentAqua'],axisFontPt:18},table:{headerFillRole:'headingPrimary',headerTextRole:'canvasPrimary',fontPt:20,paddingPt:12}}},language:{organization:{toneStatus:'unspecified'},authorVoice:{status:'unselected'}}};c.revision=contractRevision(c);return c;}
test('mixed plan compiles each relationship independently; preserves content, provenance and safe regions',()=>{const c=syntheticBrand(),{scene,report}=compileDeckPlan(plan,c);assert.equal(scene.slides.length,11);assert.equal(new Set(report.choices.map(s=>s.component)).size,11);assert.ok(scene.slides[7].elements.some(e=>e.type==='table'));assert.ok(scene.slides[8].elements.some(e=>e.type==='chart'&&e.series[0].values.includes(-8)));assert.ok(scene.slides[5].elements.some(e=>e.type==='line'&&e.arrow));assert.ok(scene.slides[6].elements.some(e=>e.text?.includes('not a measured product result')));for(const s of scene.slides)for(const e of s.elements)assert.ok(e.y+e.height<=486);assert.ok(!report.findings.some(f=>f.code==='contrast'));assert.equal(report.brandRevision,c.revision);});
test('rejects evidence loss, schema typos, unknown content and unresolved assets; warns on fit',()=>{let p=structuredClone(plan);p.slides[0].intent.evidence=['missing'];assert.throws(()=>inspectDeckPlan(p),/evidence/);p=structuredClone(plan);p.slides[0].component.extraFact='lost';assert.throws(()=>inspectDeckPlan(p),/silently/);p=structuredClone(plan);p.slides[0].intent.relationship='comparison';assert.throws(()=>inspectDeckPlan(p),/does not express/);p=structuredClone(plan);delete p.assets.latency.src;p.assets.latency.request={prompt:'Generate an illustrative curve'};assert.equal(inspectDeckPlan(p).assetNeeds.length,1);assert.throws(()=>compileDeckPlan(p,syntheticBrand()),/image needs/);p=structuredClone(plan);p.slides[1].component.columns[0].text='Too many words '.repeat(70);assert.ok(compileDeckPlan(p,syntheticBrand()).report.findings.some(f=>f.code==='estimated-text-fit'));});
test('contract enforces source drift, medium isolation and provisional voice state',async t=>{const dir=await temporary(t),source=join(dir,'policy.json');await writeFile(source,'authority');const c=syntheticBrand();c.sources=[{path:source,sha256:hash(await readFile(source))}];c.revision=contractRevision(c);await checkBrandSources(c);await writeFile(source,'new authority');await assert.rejects(()=>checkBrandSources(c),/authority changed/);const blog=structuredClone(c);blog.medium.kind='blog';blog.revision=contractRevision(blog);assert.throws(()=>validateBrandContract(blog),/inherit slide/);delete blog.design.slides;blog.language.authorVoice={id:'test-author',status:'provisional',guide:'Use the supplied examples.',sha256:'b'.repeat(64)};blog.revision=contractRevision(blog);validateBrandContract(blog);assert.equal(blog.language.authorVoice.status,'provisional');blog.design.colors.inkDeep='#000000';assert.throws(()=>validateBrandContract(blog),/changed/);});
test('file compilation hashes assets, refuses overwrite and produces a handoff',async t=>{const dir=await temporary(t),source=join(dir,'source.txt'),brand=join(dir,'brand.json');await writeFile(source,'authority');const c=syntheticBrand();c.sources=[{path:source,sha256:hash(await readFile(source))}];c.revision=contractRevision(c);await writeFile(brand,JSON.stringify(c));const output=join(dir,'compiled');await compileDeckFile({file:fileURLToPath(new URL('../examples/deck-plan.json',import.meta.url)),brand,output});const report=JSON.parse(await readFile(join(output,'design-report.json')));assert.equal(report.inputs.assets.length,1);await assert.rejects(()=>compileDeckFile({file:fileURLToPath(new URL('../examples/deck-plan.json',import.meta.url)),brand,output}),/EEXIST/);});
test('Google tables use explicit translation, brand colors and unequal native column widths',()=>{const {scene}=compileDeckPlan(plan,syntheticBrand());scene.slides=scene.slides.filter(s=>s.id==='table_slide');const e=scene.slides[0].elements.find(e=>e.type==='table');e.columnWidths=[264,300,300];const deck={presentationId:'test_deck',revisionId:'r1',pageSize:{width:{magnitude:960,unit:'PT'},height:{magnitude:540,unit:'PT'}},slides:[]};const built=compileGoogleScene(scene,deck);assert.deepEqual(built.requests.find(r=>r.createTable).createTable.elementProperties,{pageObjectId:'table_slide'});assert.equal(built.requests.find(r=>r.updatePageElementTransform).updatePageElementTransform.transform.translateX,48);assert.deepEqual(built.requests.filter(r=>r.updateTableColumnProperties).map(r=>r.updateTableColumnProperties.tableColumnProperties.columnWidth.magnitude),[264,300,300]);assert.ok(built.limitations.some(x=>x.detail.includes('padding')));const chartScene=compileDeckPlan(plan,syntheticBrand()).scene;chartScene.slides=chartScene.slides.filter(s=>s.id==='chart_slide');chartScene.slides[0].elements.find(e=>e.type==='chart').sheetsChart={spreadsheetId:'test_sheet',chartId:1};assert.ok(compileGoogleScene(chartScene,deck).limitations.some(x=>x.detail.includes('Sheets source styling')));const after={slides:scene.slides.map(s=>({objectId:s.id,pageElements:s.elements.map(e=>({objectId:e.id,size:{width:{magnitude:e.width,unit:'PT'},height:{magnitude:e.height,unit:'PT'}},transform:{scaleX:1,scaleY:1,translateX:e.x,translateY:e.y,unit:'PT'},...(e.type==='table'?{table:{rows:e.rows.length,columns:3,tableColumns:e.columnWidths.map(v=>({columnWidth:{magnitude:v,unit:'PT'}})),tableRows:e.rows.map((row,ri)=>({rowHeight:{magnitude:e.height/e.rows.length,unit:'PT'},tableCells:row.map((v,ci)=>({location:{rowIndex:ri,columnIndex:ci},text:nativeText(v,e.fontSize)}))}))}}:{shape:{text:nativeText(e.text,e.fontSize)}})}))}))};verifyGoogleSceneReadback(scene,after);after.slides[0].pageElements.find(x=>x.table).table.tableRows[1].tableCells[0].text=nativeText('Dropped content',20);assert.throws(()=>verifyGoogleSceneReadback(scene,after),/text content/);});
function nativeText(text,size){return {textElements:[{textRun:{content:text+'\n',style:{fontFamily:'Arial',fontSize:{magnitude:size,unit:'PT'}}}}]};}
test('native mixed PPTX retains negative chart data, orientation controls, table colors and notes',async t=>{const dir=await temporary(t),p=structuredClone(plan);delete p.assets;p.slides=p.slides.filter(s=>s.component.kind!=='image');p.slides[0].notes='Source and caveat remain in speaker notes.';const {scene}=compileDeckPlan(p,syntheticBrand());scene.slides[0].elements[1].fill='#ABCDEF';const out=join(dir,'mixed.pptx');const rendered=await renderPptxScene(scene,out);assert.equal(rendered.slides,10);const {stdout:textXml}=await exec('unzip',['-p',out,'ppt/slides/slide1.xml']);assert.match(textXml,/<a:solidFill><a:srgbClr val="ABCDEF"/);const {stdout:chart}=await exec('unzip',['-p',out,'ppt/charts/chart1.xml']);assert.ok(Number(chart.match(/<c:min val="([^"]+)"/)[1]) < -8);assert.match(chart,/<c:v>-8<\/c:v>/);const {stdout:table}=await exec('unzip',['-p',out,'ppt/slides/slide8.xml']);assert.match(table,/2867B2/);const {stdout:notes}=await exec('unzip',['-p',out,'ppt/notesSlides/notesSlide1.xml']);assert.match(notes,/Source and caveat/);});

test('default content-led generation works without installing a brand add-on',async t=>{const dir=await temporary(t),output=join(dir,'compiled');await compileDeckFile({file:fileURLToPath(new URL('../examples/deck-plan.json',import.meta.url)),output});const c=JSON.parse(await readFile(join(output,'brand-contract.json')));assert.equal(c.identity.id,'unbranded');assert.equal(c.design.nativeTemplate,undefined);const scene=JSON.parse(await readFile(join(output,'scene.json')));await renderPptxScene(scene,join(dir,'deck.pptx'),{brand:c});});

test('workspace exposes Google style limits and refuses changed brand authority after build',async t=>{const dir=await temporary(t),source=join(dir,'authority.txt'),contract=syntheticBrand();await writeFile(source,'authority');contract.sources=[{path:source,sha256:hash(await readFile(source))}];contract.revision=contractRevision(contract);const p=structuredClone(plan);p.slides=p.slides.filter(s=>s.id==='table_slide');delete p.assets;const {scene}=compileDeckPlan(p,contract),template=join(dir,'template.json');await writeFile(template,JSON.stringify({presentationId:'test_deck',revisionId:'r1',pageSize:{width:{magnitude:960,unit:'PT'},height:{magnitude:540,unit:'PT'}},slides:[]}));const root=join(dir,'workspace');await initWorkspace({root,scene,format:'google-slides',template,brandContract:contract});const built=await buildWorkspace({root});assert.ok(built.limitations.some(x=>x.detail.includes('padding')));await verifiedBuild(root);await writeFile(source,'changed authority');await assert.rejects(()=>verifiedBuild(root),/authority changed/);});
