import test from 'node:test';import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,realpath,symlink} from 'node:fs/promises';
import {join} from 'node:path';import {fileURLToPath} from 'node:url';
import {execFile} from 'node:child_process';import {promisify} from 'node:util';
import {runtimeVersion} from '../scripts/lib/runtime-version.mjs';import {initWorkspace,loadWorkspace,saveScene} from '../scripts/lib/workspace.mjs';
import {sceneFixture,temporary} from './fixtures.mjs';
const exec=promisify(execFile),cli=fileURLToPath(new URL('../scripts/harness-slides.mjs',import.meta.url)),pkg=JSON.parse(await readFile(new URL('../package.json',import.meta.url)));
test('version checks the executing package offline, regardless of content-project version',async t=>{const dir=await temporary(t);await writeFile(join(dir,'package.json'),JSON.stringify({name:'unrelated-project',version:'99.0.0'}));const human=await exec(process.execPath,[cli,'--version'],{cwd:dir});assert.equal(human.stdout.trim(),'Harness Slides '+pkg.version);const record=JSON.parse((await exec(process.execPath,[cli,'version'],{cwd:dir})).stdout);assert.equal(record.runtimeVersion,pkg.version);assert.equal(record.package,pkg.name);assert.equal(record.runtime,await realpath(fileURLToPath(new URL('../',import.meta.url))));});
test('version resolves the selected runtime and rejects invalid identities',async t=>{const dir=await temporary(t),old=join(dir,'old'),link=join(dir,'selected');await mkdir(old);await writeFile(join(old,'package.json'),JSON.stringify({name:pkg.name,version:'0.2.0'}));await symlink(old,link);assert.equal((await runtimeVersion(link)).runtimeVersion,'0.2.0');assert.equal((await runtimeVersion(link)).runtime,await realpath(old));await writeFile(join(old,'package.json'),JSON.stringify({name:'other',version:'0.2.0'}));await assert.rejects(()=>runtimeVersion(link),/Unrecognized/);});
test('standalone version reporting does not reinterpret workspace restore version flags',async()=>{await assert.rejects(()=>exec(process.execPath,[cli,'version','extra']),/no action/);await assert.rejects(()=>exec(process.execPath,[cli,'version','--version','v000001']),/not valid/);});

test('workspace restore still accepts its existing --version ID after adding --version reporting',async t=>{const dir=await temporary(t),root=join(dir,'workspace'),s=await sceneFixture();await initWorkspace({root,scene:s,format:'pptx'});const first=await loadWorkspace(root);s.slides[0].elements[0].text='A revised synthetic title';await saveScene({root,scene:s,expectedDigest:first.current.sceneDigest});const current=await loadWorkspace(root),restored=JSON.parse((await exec(process.execPath,[cli,'workspace','restore','--project',root,'--version','v000001','--expected',current.current.sceneDigest])).stdout);assert.equal(restored.id,'v000003');assert.equal((await loadWorkspace(root)).scene.slides[0].elements[0].text,first.scene.slides[0].elements[0].text);});
