// Content-owned intermediate. Each component compiles independently into editable objects.
import {readFile,mkdir,writeFile,rm} from 'node:fs/promises';
import {resolve,dirname,join} from 'node:path';
import {validateScene,sceneFindings} from './scene.mjs';
import {brandTheme,validateBrandContract,checkBrandSources,neutralBrandContract} from './brand-contract.mjs';
import {validateSlideDecision} from './slide-decisions.mjs';
import {digest,hash} from './common.mjs';
const kinds={statement:['text','support'],comparison:['columns','variant'],categories:['items','variant'],process:['steps'],timeline:['events'],architecture:['nodes','edges'],metric:['value','label','context','qualifier'],table:['rows','columnWidths','caption'],chart:['chartType','series','source','sheetsChart','caption'],quote:['text','attribution','context'],image:['asset','caption','callouts','explanation'],scope:['regions','caption'],decision:['nodes','edges','caption'],'paired-diagram':['panels','caption'],evidence:['finding','explanation','qualifier']};
const relationships={statement:['claim'],comparison:['comparison'],categories:['categories'],process:['sequence'],timeline:['time'],architecture:['system'],metric:['quantity'],table:['comparison','reference'],chart:['quantity','trend','comparison'],quote:['testimony'],image:['image','system'],scope:['responsibility','containment'],decision:['decision'],'paired-diagram':['comparison'],evidence:['claim','testimony']};
const id=/^[a-zA-Z_][a-zA-Z0-9_-]{4,32}$/;
const text=(v,name)=>{if(typeof v!=='string'||!v.trim()||v.length>20000)throw new Error(`Provide ${name}`);};
const fields=(o,keys,name)=>{if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).some(k=>!keys.includes(k)))throw new Error(`Unsupported ${name} field; never silently drop content`);};
const list=(v,min,max,name)=>{if(!Array.isArray(v)||v.length<min||v.length>max)throw new Error(`${name} needs ${min}–${max} items`);};
export function componentContract(kind) {
  if(kind&&!kinds[kind])throw new Error('Unknown component');
  const result={schema:2,plan:'{schema:2,title,assets?:{id:{src?,alt,request?:{prompt,reference?}}},slides:[{id,title,sources,intent:{takeaway,relationship,rationale,evidence,audienceQuestion,alternative:{treatment,reason},visual:{family,purpose,route?}},component:{kind,...},notes?,layoutId?}]}',components:Object.fromEntries(Object.entries(kinds).filter(([key])=>!kind||key===kind).map(([key,keys])=>[key,{fields:keys,relationships:relationships[key]}])),details:{scope:'regions:[{label,text}] (2–3). Side-by-side labeled ownership/scope, never invented nesting.',decision:'nodes:[{id,label,text?,x:0..1,y:0..1}] (2–7); edges:[{from,to,label}] (1–10). Explicit branch facts; caption retains caveats.', 'paired-diagram':'panels:[{label,nodes:[{id,label,x:0..1,y:0..1}],edges:[{from,to,label}]}] (exactly 2; 2–5 nodes each). Matched actors; sourced connections.',evidence:'finding, explanation, qualifier: text. Asymmetric evidence/explanation; no invented quantities.',comparison:'columns:[{label,text}] (2–3); variant: cards (legacy), open, rows',categories:'items:[{label,text}] (2–4); variant: cards (legacy), open',process:'steps:[{label,text}] (2–5)',timeline:'events:[{date,label,text}] (2–5)',architecture:'nodes:[{id,label,text?,tier:0..2}] (2–9, max 3/tier); edges:[{from,to,label?}]',image:'asset:asset ID; callouts?:[{label,x:0..1,y:0..1}] (max 3; coordinates within image)',assets:'Local images resolve relative to plan; Google needs public HTTPS. Unresolved requests are reported by deck inspect; compile refuses missing images. Native approved icons use the brand icon helper.',other:'Rows are rectangular strings; chart data uses scene series. Optional captions/notes retain qualifiers. Every intent evidence reference must appear in slide sources.'},output:'Editable scene + intent/fit report + source hashes. Estimates require native rendered review. No automatic layout alternation or forced decoration.'};
  if(kind)result.details=Object.fromEntries(Object.entries(result.details).filter(([key])=>key===kind||key==='other'||kind==='image'&&key==='assets'));return result;
}
export function inspectDeckPlan(plan) {
  fields(plan,['schema','title','slides','assets'],'plan');if(![1,2].includes(plan.schema))throw new Error('Use deck plan schema 1 or 2');text(plan.title,'deck title');list(plan.slides,1,100,'slides');
  const assets=plan.assets??{};fields(assets,Object.keys(assets),'assets');const needs=[],used=new Set(),ids=new Set();
  for(const s of plan.slides){fields(s,['id','title','sources','intent','component','notes','layoutId'],'slide');if(!id.test(s.id??'')||ids.has(s.id))throw new Error('Use unique stable slide IDs (5–33 characters)');ids.add(s.id);text(s.title,'slide title');list(s.sources,1,100,'sources');s.sources.forEach(v=>text(v,'source'));if(s.notes!==undefined&&typeof s.notes!=='string')throw new Error('Notes must be text');
    validateSlideDecision(s.intent,s.sources,{required:plan.schema===2});
    const c=s.component;if(!kinds[c?.kind])throw new Error('Select a supported component for each slide');fields(c,['kind',...kinds[c.kind]],'component');if(!relationships[c.kind].includes(s.intent.relationship))throw new Error(`${c.kind} does not express ${s.intent.relationship}; select from content`);
    if(c.variant!==undefined&&!({comparison:['cards','open','rows'],categories:['cards','open']}[c.kind]??[]).includes(c.variant))throw new Error('Unsupported composition variant');
    if(['statement','quote'].includes(c.kind)){text(c.text,'component text');if(c.kind==='quote')text(c.attribution,'quote attribution');}
    if(['comparison','categories','process','timeline'].includes(c.kind)){const key={comparison:'columns',categories:'items',process:'steps',timeline:'events'}[c.kind];list(c[key],2,{comparison:3,categories:4,process:5,timeline:5}[c.kind],key);for(const item of c[key]){fields(item,c.kind==='timeline'?['date','label','text']:['label','text'],key);text(item.label,'label');text(item.text,'item text');if(c.kind==='timeline')text(item.date,'event date');}}
    if(c.kind==='metric'){for(const key of ['value','label','context','qualifier'])text(c[key],`metric ${key}`);}
    if(c.kind==='architecture'){list(c.nodes,2,9,'nodes');list(c.edges,0,20,'edges');const nodes=new Map();for(const n of c.nodes){fields(n,['id','label','text','tier'],'node');if(!id.test(n.id??'')||nodes.has(n.id)||!Number.isInteger(n.tier)||n.tier<0||n.tier>2)throw new Error('Architecture needs unique nodes and tiers 0–2');nodes.set(n.id,n);text(n.label,'node label');if(n.text!==undefined)text(n.text,'node text');}for(let tier=0;tier<3;tier++)if(c.nodes.filter(n=>n.tier===tier).length>3)throw new Error('Split architecture: maximum three nodes per tier');for(const e of c.edges){fields(e,['from','to','label'],'edge');if(!nodes.has(e.from)||!nodes.has(e.to)||e.from===e.to)throw new Error('Architecture edges need distinct existing nodes');if(e.label!==undefined)text(e.label,'edge label');}}
    if(['scope','decision','paired-diagram','evidence'].includes(c.kind))validateConstruction(c);
    if(c.explanation!==undefined)text(c.explanation,'image explanation');
    if(c.kind==='image'){text(c.asset,'asset ID');const a=assets[c.asset];if(!a)throw new Error(`Define asset ${c.asset}`);fields(a,['src','alt','request','metadata'],'asset');text(a.alt,'image alt text');if(a.request){fields(a.request,['prompt','reference'],'image request');text(a.request.prompt,'image prompt');}if(a.metadata!==undefined)text(a.metadata,'image metadata path');if(a.src)text(a.src,'asset path');else needs.push({slide:s.id,asset:c.asset,kind:'image',request:a.request??null,metadata:a.metadata??null});used.add(c.asset);if(c.callouts){list(c.callouts,0,3,'callouts');for(const x of c.callouts){fields(x,['label','x','y'],'callout');text(x.label,'callout label');if(!Number.isFinite(x.x)||!Number.isFinite(x.y)||x.x<0||x.x>1||x.y<0||x.y>1)throw new Error('Callouts need normalized image coordinates');}}}
    if(c.kind==='chart'){text(c.source,'chart source');list(c.series,1,20,'series');for(const v of c.series){fields(v,['name','labels','values'],'chart series');text(v.name,'series name');}if(c.series.some(v=>JSON.stringify(v.labels)!==JSON.stringify(c.series[0].labels)))throw new Error('Chart series must share ordered category labels');if(c.sheetsChart)fields(c.sheetsChart,['spreadsheetId','chartId'],'linked chart');}
    if(s.layoutId!==undefined)text(s.layoutId,'native layout ID');
    for(const key of ['support','context','caption'])if(c[key]!==undefined)text(c[key],key);
  }
  for(const key of Object.keys(assets))if(!used.has(key))throw new Error(`Unused asset ${key}; remove it or use it explicitly`);
  return {schema:plan.schema,title:plan.title,slides:plan.slides.map(s=>({id:s.id,component:s.component.kind,variant:s.component.variant??null,intent:s.intent})),assetNeeds:needs,status:needs.length?'assets required':'ready to compile; native review required'};
}
export function compileDeckPlan(plan,contract) {
  const inspected=inspectDeckPlan(plan);validateBrandContract(contract,{medium:'slides'});if(inspected.assetNeeds.length)throw new Error('Resolve image needs from deck inspect before compilation');
  const d=contract.design,b=d.slides.contentBox,t=d.slides.typography,col=d.colors,sp=d.slides.spacing??{},gap=sp.column??30,inset=sp.inset??18,body=contract.medium.delivery==='live'?'body':'bodyReference',findings=[],scene={version:2,title:plan.title,mode:'new',canvas:d.slides.canvas,theme:brandTheme(contract),slides:[]};
  const assetUses=[],intentionalOverlaps=[];
  for(const s of plan.slides){let serial=0;const elements=[],uid=()=>`${s.id}_${String(++serial).padStart(3,'0')}`,put=(type,box,rest)=>{const e={id:uid(),type,...box,...rest};elements.push(e);return e;};
    const txt=(value,box,role=body,extra={})=>{const style=t[role],e=put('text',box,{text:value,fontSize:style.size,bold:style.bold,color:col[style.colorRole],...extra});const available=Math.max(1,box.width-7.2),lines=value.split('\n').reduce((n,line)=>n+Math.max(1,Math.ceil([...line].reduce((w,c)=>w+(/[MW@%]/.test(c)?.85:/[il., ']/.test(c)?.27:.53),0)*e.fontSize/available)),0);if(lines*e.fontSize*1.25+7.2>box.height)findings.push({slide:s.id,object:e.id,severity:'warn',code:'estimated-text-fit',detail:`${role}: estimated ${lines} lines exceed allocated height; rewrite, split or change composition; verify native render`});return e;};
    const rect=(box,fill=col.canvasSecondary)=>put('shape',box,{shape:'rect',fill});
    const line=(x1,y1,x2,y2,arrow=false)=>put('line',{x:Math.min(x1,x2),y:Math.min(y1,y2),width:Math.max(1,Math.abs(x2-x1)),height:Math.max(1,Math.abs(y2-y1))},{color:col.headingPrimary,weight:2,arrow,flipH:x2<x1,flipV:y2<y1});
    const caption=(value)=>{if(value)txt(value,{x:b.x,y:b.y+b.height-32,width:b.width,height:32},'caption');};
    txt(s.title,d.slides.titleBox,'title');const c=s.component;
    if(c.kind==='statement'){txt(c.text,{...b,height:c.support?b.height*.62:b.height},'quote');if(c.support)txt(c.support,{...b,y:b.y+b.height*.7,height:b.height*.3});}
    else if(c.kind==='comparison'&&c.variant==='rows'){const n=c.columns.length,h=(b.height-gap*(n-1))/n;c.columns.forEach((v,i)=>{const y=b.y+i*(h+gap);rect({x:b.x,y,width:5,height:h},col.headingPrimary);txt(v.label,{x:b.x+inset,y,width:b.width*.27-inset,height:h},'label');txt(v.text,{x:b.x+b.width*.3,y,width:b.width*.7,height:h});});}
    else if((c.kind==='comparison'||c.kind==='categories')&&c.variant==='open'){const items=c.columns??c.items,w=(b.width-gap*(items.length-1))/items.length;items.forEach((v,i)=>{const x=b.x+i*(w+gap);txt(v.label,{x,y:b.y,width:w,height:70},'label');line(x,b.y+82,x+w,b.y+82);txt(v.text,{x,y:b.y+100,width:w,height:b.height-100});});}
    else if(c.kind==='comparison'||c.kind==='categories'){const items=c.columns??c.items,n=items.length,w=(b.width-gap*(n-1))/n;items.forEach((v,i)=>{const x=b.x+i*(w+gap);rect({x,y:b.y,width:w,height:b.height});rect({x,y:b.y,width:w,height:6},col.headingPrimary);txt(v.label,{x:x+inset,y:b.y+inset,width:w-2*inset,height:58},'label');txt(v.text,{x:x+inset,y:b.y+88,width:w-2*inset,height:b.height-88-inset});});}
    else if(c.kind==='process'){const n=c.steps.length,w=(b.width-gap*(n-1))/n;c.steps.forEach((v,i)=>{const x=b.x+i*(w+gap);rect({x,y:b.y+20,width:w,height:82},col.headingPrimary);txt(v.label,{x:x+8,y:b.y+25,width:w-16,height:72},'label',{color:col.canvasPrimary,fill:col.headingPrimary,align:'center'});txt(v.text,{x,y:b.y+120,width:w,height:b.height-120});if(i<n-1)line(x+w+2,b.y+61,x+w+gap-4,b.y+61,true);});}
    else if(c.kind==='timeline'){const n=c.events.length,w=(b.width-gap*(n-1))/n;line(b.x,b.y+86,b.x+b.width,b.y+86);c.events.forEach((v,i)=>{const x=b.x+i*(w+gap);txt(v.date,{x,y:b.y,width:w,height:52},'label');put('shape',{x:x+w/2-5,y:b.y+81,width:10,height:10},{shape:'ellipse',fill:col.headingPrimary});txt(v.label,{x,y:b.y+108,width:w,height:64},'label');txt(v.text,{x,y:b.y+184,width:w,height:b.height-184});});}
    else if(c.kind==='architecture'){const tiers=[...new Set(c.nodes.map(n=>n.tier))].sort(),h=(b.height-(tiers.length-1)*gap)/tiers.length,boxes=new Map();tiers.forEach((tier,ti)=>{const nodes=c.nodes.filter(n=>n.tier===tier),w=(b.width-gap*(nodes.length-1))/nodes.length;nodes.forEach((n,ni)=>boxes.set(n.id,{x:b.x+ni*(w+gap),y:b.y+ti*(h+gap),width:w,height:h}));});for(const e of c.edges){const a=boxes.get(e.from),z=boxes.get(e.to),same=a.y===z.y;let x1=a.x+a.width/2,y1=a.y+(z.y>=a.y?a.height:0),x2=z.x+z.width/2,y2=z.y+(z.y>=a.y?0:z.height);if(same){x1=a.x+(z.x>a.x?a.width:0);x2=z.x+(z.x>a.x?0:z.width);y1=y2=a.y+a.height/2;}line(x1,y1,x2,y2,true);if(e.label){const w=Math.min(180,gap===30?180:b.width/3);txt(e.label,{x:Math.max(b.x,Math.min(b.x+b.width-w,(x1+x2)/2-w/2)),y:Math.max(b.y,Math.min(b.y+b.height-26,(y1+y2)/2-13)),width:w,height:26},'caption',{fill:col.canvasPrimary,align:'center'});}}for(const n of c.nodes){const box=boxes.get(n.id);rect(box);txt(n.label,{x:box.x+inset,y:box.y+8,width:box.width-2*inset,height:n.text?Math.min(48,box.height*.5):box.height-16},'label',{align:'center'});if(n.text)txt(n.text,{x:box.x+inset,y:box.y+box.height*.5,width:box.width-2*inset,height:box.height*.5-8},'caption',{align:'center'});}}
    else if(c.kind==='scope'){const w=(b.width-gap*(c.regions.length-1))/c.regions.length;c.regions.forEach((v,i)=>{const x=b.x+i*(w+gap),h=b.height-(c.caption?48:0);rect({x,y:b.y,width:w,height:h});txt(v.label,{x:x+inset,y:b.y+inset,width:w-2*inset,height:60},'label');line(x+inset,b.y+90,x+w-inset,b.y+90);txt(v.text,{x:x+inset,y:b.y+110,width:w-2*inset,height:h-110-inset});});caption(c.caption);}
    else if(c.kind==='decision'||c.kind==='paired-diagram'){
      const panels=c.kind==='decision'?[{nodes:c.nodes,edges:c.edges}]:c.panels,w=(b.width-gap*(panels.length-1))/panels.length;
      panels.forEach((p,i)=>{const x=b.x+i*(w+gap),top=b.y+(p.label?60:0),h=b.height-(p.label?60:0)-(c.caption?48:0),nw=Math.min(220,w*.42),nh=Math.min(80,h*.24),boxes=new Map();if(p.label)txt(p.label,{x,y:b.y,width:w,height:50},'label');
        for(const n of p.nodes)boxes.set(n.id,{x:x+n.x*(w-nw),y:top+n.y*(h-nh),width:nw,height:nh});
        for(const e of p.edges){const a=boxes.get(e.from),z=boxes.get(e.to),horizontal=Math.abs(z.x-a.x)>Math.abs(z.y-a.y),right=z.x>a.x,down=z.y>a.y;const x1=horizontal?a.x+(right?a.width:0):a.x+a.width/2,y1=horizontal?a.y+a.height/2:a.y+(down?a.height:0),x2=horizontal?z.x+(right?0:z.width):z.x+z.width/2,y2=horizontal?z.y+z.height/2:z.y+(down?0:z.height);line(x1,y1,x2,y2,true);const ew=Math.min(140,w*.32,Math.max(44,e.label.length*t.caption.size*.65+12));txt(e.label,{x:Math.max(x,Math.min(x+w-ew,(x1+x2)/2-ew/2)),y:Math.max(top,Math.min(top+h-28,(y1+y2)/2-14)),width:ew,height:28},'caption',{fill:col.canvasPrimary,align:'center'});}
        for(const n of p.nodes){const box=boxes.get(n.id);rect(box);txt(n.label,{...box,x:box.x+6,width:box.width-12,height:n.text?box.height*.55:box.height},'label',{align:'center'});if(n.text)txt(n.text,{x:box.x+6,y:box.y+box.height*.55,width:box.width-12,height:box.height*.45},'caption',{align:'center'});}
      });caption(c.caption);
    }
    else if(c.kind==='evidence'){txt(c.finding,{...b,width:b.width*.42,height:b.height-54},'quote');rect({x:b.x+b.width*.45,y:b.y,width:5,height:b.height-54},col.headingPrimary);txt(c.explanation,{x:b.x+b.width*.5,y:b.y,width:b.width*.5,height:b.height-54});caption(c.qualifier);}
    else if(c.kind==='metric'){txt(c.value,{...b,width:b.width*.47,height:116},'metric');txt(c.label,{...b,y:b.y+130,width:b.width*.47,height:90},'label');rect({x:b.x+b.width*.52,y:b.y,width:b.width*.48,height:b.height-54});txt(c.context,{x:b.x+b.width*.52+inset,y:b.y+inset,width:b.width*.48-2*inset,height:b.height-54-2*inset});caption(c.qualifier);}
    else if(c.kind==='table'){const widths=c.columnWidths??c.rows?.[0]?.map(()=>b.width/c.rows[0].length),rowHeight=(b.height-(c.caption?40:0))/(c.rows?.length??1),padding=d.slides.table.paddingPt??12,font=d.slides.table.fontPt??t[body].size;for(const [ri,row] of (c.rows??[]).entries())for(const [ci,value] of row.entries()){if(typeof value==='string'&&Math.ceil(value.length*font*.53/Math.max(1,widths[ci]-2*padding))*font*1.25+2*padding>rowHeight)findings.push({slide:s.id,severity:'warn',code:'estimated-table-fit',detail:`Row ${ri+1}, column ${ci+1}: inspect wrapping and row expansion; split dense tables`});}put('table',{...b,height:b.height-(c.caption?40:0)},{rows:c.rows,fontSize:d.slides.table.fontPt??t[body].size,color:col.inkDeep,headerFill:col[d.slides.table.headerFillRole],headerColor:col[d.slides.table.headerTextRole],bodyFill:col.canvasPrimary,padding:d.slides.table.paddingPt??12,...(c.columnWidths?{columnWidths:c.columnWidths}:{})});caption(c.caption);}
    else if(c.kind==='chart'){put('chart',{...b,height:b.height-40},{chartType:c.chartType,series:c.series,source:c.source,...(c.sheetsChart?{sheetsChart:c.sheetsChart}:{}),colors:d.slides.chart.seriesRoles.map(r=>col[r]),labelSize:d.slides.chart.axisFontPt??18});caption(c.caption??c.source);}
    else if(c.kind==='quote'){txt(c.text,{...b,height:b.height*.64},'quote');txt(c.attribution,{...b,y:b.y+b.height*.68,height:54},'label');if(c.context)caption(c.context);}
    else if(c.kind==='image'){const a=plan.assets[c.asset],box={...b,width:c.explanation?(b.width-gap)*.6:b.width,height:b.height-(c.caption?40:0)};const e=put('image',box,{src:a.src,alt:a.alt,fit:'contain'});if(c.explanation)txt(c.explanation,{x:b.x+box.width+gap,y:b.y,width:b.width-box.width-gap,height:box.height});assetUses.push({slide:s.id,object:e.id,asset:c.asset,src:a.src,alt:a.alt,request:a.request??null,metadata:a.metadata??null});for(const x of c.callouts??[]){const w=Math.min(220,b.width*.3),h=44;const annotation=txt(x.label,{x:Math.min(box.x+box.width-w,box.x+x.x*box.width),y:Math.min(box.y+box.height-h,box.y+x.y*box.height),width:w,height:h},'label',{fill:col.canvasPrimary});intentionalOverlaps.push({slide:s.id,front:annotation.id,back:e.id,reason:'Editable image annotation with a solid background'});}caption(c.caption);}
    scene.slides.push({...(plan.schema===2?{intent:s.intent}:{}),id:s.id,title:s.title,sources:s.sources,elements,...(s.notes!==undefined?{notes:s.notes}:{}),...(s.layoutId?{layoutId:s.layoutId}:{})});
  }
  validateScene(scene);findings.push(...sceneFindings(scene));
  const choices=plan.slides.map(s=>({id:s.id,component:s.component.kind,variant:s.component.variant??null,intent:s.intent}));for(let i=2;i<choices.length;i++)if(choices[i].component===choices[i-1].component&&choices[i].component===choices[i-2].component)findings.push({slide:choices[i].id,severity:'info',code:'repeated-composition',detail:'Three repeated components: confirm each is justified by its content; do not alternate mechanically'});
  return {scene,report:{schema:plan.schema,brandRevision:contract.revision,planDigest:digest(plan),choices,assetUses,intentionalOverlaps,findings,status:'unreviewed draft; fit is estimated',limitations:['Native render and visual inspection required','Diagram edges are editable lines; automatic attachment on node movement is not supported']}};
}
export async function compileDeckFile({file,brand,output,fonts}){
  const planBytes=await readFile(file),brandBytes=brand?await readFile(brand):null,plan=JSON.parse(planBytes),contract=brandBytes?JSON.parse(brandBytes):await neutralBrandContract();await checkBrandSources(contract);const {scene,report}=compileDeckPlan(plan,contract),assets=[];
  for(const s of scene.slides)for(const e of s.elements)if(e.type==='image'&&!/^https:\/\//.test(e.src)){const path=resolve(dirname(resolve(file)),e.src),bytes=await readFile(path);e.src=path;const use=report.assetUses.find(a=>a.object===e.id),record={object:e.id,path,sha256:hash(bytes)};
    if(use?.metadata){const metadataPath=resolve(dirname(resolve(file)),use.metadata),metaBytes=await readFile(metadataPath),m=JSON.parse(metaBytes);if(m.generated!==true||m.provider!=='gemini-web'||m.sha256!==record.sha256||!bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]))||m.width!==bytes.readUInt32BE(16)||m.height!==bytes.readUInt32BE(20))throw new Error('Generated-image provenance/dimensions do not match the local PNG');record.provenance={provider:m.provider,generated:true,width:m.width,height:m.height,sha256:m.sha256,libraryRevision:m.libraryRevision,model:m.model,requestId:m.requestId,promptSha256:m.promptSha256,referenceSha256:m.referenceSha256};record.metadataSha256=hash(metaBytes);}
    else if(plan.schema===2&&(use?.request||s.intent?.visual?.family==='generated-art'))throw new Error('Retain generated-image metadata before compiling a resolved request');assets.push(record);}
  report.inputs={plan:{path:resolve(file),sha256:hash(planBytes)},brand:brand?{path:resolve(brand),sha256:hash(brandBytes)}:{kind:'neutral defaults',revision:contract.revision},assets};report.sceneDigest=digest(scene);
  const {auditSceneQuality}=await import('./slide-quality.mjs'),quality=await auditSceneQuality(scene,{designReport:report,fonts:fonts?JSON.parse(await readFile(fonts)):undefined});
  report.findings=[...report.findings.filter(f=>!['estimated-text-fit','estimated-table-fit','density','text-only','small-text','contrast'].includes(f.code)),...quality.findings];report.fontEvidence=quality.fontEvidence;report.status='font-backed screening; structured critique and native review required';
  output=resolve(output);await mkdir(output,{mode:0o700});try{for(const [name,value] of [['scene.json',scene],['design-report.json',report],['brand-contract.json',contract],['quality-report.json',quality]])await writeFile(join(output,name),JSON.stringify(value,null,2)+'\n',{flag:'wx',mode:0o600});}catch(e){await rm(output,{recursive:true,force:true});throw e;}
  return {output,slides:scene.slides.length,brandRevision:contract.revision,sceneDigest:report.sceneDigest,findings:report.findings,status:report.status};
}

function validateConstruction(c) {
  if(c.kind==='evidence'){for(const key of ['finding','explanation','qualifier'])text(c[key],key);return;}
  if(c.kind==='scope'){list(c.regions,2,3,'regions');for(const r of c.regions){fields(r,['label','text'],'region');text(r.label,'scope label');text(r.text,'scope responsibilities');}return;}
  if(c.kind==='paired-diagram'){list(c.panels,2,2,'paired panels');for(const p of c.panels){fields(p,['label','nodes','edges'],'panel');text(p.label,'panel label');}}
  for(const p of c.kind==='decision'?[c]:c.panels){list(p.nodes,2,c.kind==='decision'?7:5,'nodes');list(p.edges,1,10,'edges');const ids=new Set();for(const n of p.nodes){fields(n,['id','label','text','x','y'],'positioned node');if(!id.test(n.id??'')||ids.has(n.id))throw new Error('Use unique node IDs per diagram');ids.add(n.id);text(n.label,'node label');if(n.text!==undefined)text(n.text,'node text');if(['x','y'].some(k=>!Number.isFinite(n[k])||n[k]<0||n[k]>1))throw new Error('Node positions must be normalized 0–1');}for(const e of p.edges){fields(e,['from','to','label'],'edge');if(!ids.has(e.from)||!ids.has(e.to)||e.from===e.to)throw new Error('Diagram edges require distinct existing nodes');text(e.label,'supported edge label');}}
}
